apiVersion: v1
kind: Pod
metadata:
  name: payment-service
  labels:
    app.kubernetes.io/name: payment-service
spec:
  containers:
    - name: payment-service
      image: f2js/paymentsystem
      ports:
        - containerPort: 9090
      env:
        - name: CLUSTER_IP
          value: ${CLUSTER_IP}
  hostAliases:
    - ip: ${CLUSTER_IP}
      hostnames:
        - "kafka-broker"