// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentSystem.proto

package exam.paymentsystem;

public final class PaymentSystem {
  private PaymentSystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exam_paymentsystem_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exam_paymentsystem_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exam_paymentsystem_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exam_paymentsystem_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PaymentSystem.proto\022\022exam.paymentsyste" +
      "m\"5\n\016PaymentRequest\022\017\n\007orderId\030\001 \001(\t\022\022\n\n" +
      "orderPrice\030\002 \001(\t\"#\n\017PaymentResponse\022\020\n\010r" +
      "esponse\030\001 \001(\t2d\n\016PaymentService\022R\n\007payme" +
      "nt\022\".exam.paymentsystem.PaymentRequest\032#" +
      ".exam.paymentsystem.PaymentResponseB\002P\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_exam_paymentsystem_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exam_paymentsystem_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exam_paymentsystem_PaymentRequest_descriptor,
        new java.lang.String[] { "OrderId", "OrderPrice", });
    internal_static_exam_paymentsystem_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exam_paymentsystem_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exam_paymentsystem_PaymentResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
