// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentSystem.proto

package exam.paymentsystem;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exam.paymentsystem.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string orderPrice = 2;</code>
   */
  java.lang.String getOrderPrice();
  /**
   * <code>string orderPrice = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderPriceBytes();
}
