// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentSystem.proto

package exam.paymentsystem;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exam.paymentsystem.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
